version: 0.2

phases:
  pre_build:
    commands:
      - echo Instalando dependencias...
      - yarn
  build:
    commands:
      - echo Testes
      - yarn test
      - echo Buildando
      - yarn build
artifacts:
  files: "**/*"
  discard-paths: no
  base-directory: dist
